### ISSUE TITLE
support parquet version > 1

### ISSUE THREAD

**Issue by dvirtz** [dvirtz/parquets#18]
When reading parquet file generated by pyarrow v9.0.0 
See https://github.com/dvirtz/vscode-parquet-viewer/issues/55
[birthdays-v9.zip](https://github.com/dvirtz/parquets/files/9352673/birthdays-v9.zip)

**Comment by ehiggs-deliverect** [comment]
https://arrow.apache.org/docs/js/

**Comment by dvirtz** [comment]
Thanks @ehiggs-deliverect. As far as I know the arrow js API doesn't support parquet yet.

**Comment by saritvakrat** [comment]
@dvirtz is this planned to be added? we are getting error:
Error: invalid parquet version when trying to parse V2 parquet generated with pyarrow

**Comment by dvirtz** [comment]
@saritvakrat I don't plan to work on this library any more. If you want a JS parquet library you can try [parquet-wasm](https://kylebarron.dev/parquet-wasm)
