### ISSUE TITLE
"close" does not exist on - While using stream passthrough with parquets

### ISSUE THREAD

**Issue by krish-199** [dvirtz/parquets#19]

**Comment by dvirtz** [comment]
Thanks for opening the issue. 
Could you please give more details? What's the scenario you're seeing this in?

**Comment by krish-199** [comment]
It occurs when I am using stream passthrough when calling the writer.close(). On further inspection seems to be caused due to "end()" doesn't exist on the passthrough stream.
The intention of using passthrough is to save parquet buffer directly into s3, without creating any stream

**Comment by dvirtz** [comment]
I tried to reproduce it in https://github.com/dvirtz/parquets/blob/issue19-2/test/integration.ts#L548 and it seems to work ok.

**Comment by krish-199** [comment]
Thanks for the test case. The issue was caused due to, not passing a writable stream to the parquet writer.
