### ISSUE TITLE
Target PRs in here?

### ISSUE THREAD

**Issue by dobesv** [dvirtz/parquets#6]
I have some PRs and changes I have been making based on https://github.com/kbajalc/parquets but it seems that repo is dead and PRs are being ignored.

Do you think it would be a good idea for me to try and reapply those changes to this repo?  What is your plan for this repo, is it mainly just for your own use or are you interested in maintaining it?

See also https://github.com/kbajalc/parquets/issues/38

**Comment by dvirtz** [comment]
As I wrote in the original issue, I'm mainly doing bug fixes coming from my other project.
I don't plan on adding other features at this time but I'm willing to review PRs.

Are you interested in maintaining a fork? 
I can add you as a collaborator on my fork if you like.

**Comment by berenddeboer** [comment]
Yes please, @dobesv has some useful patches which would be great to get into a maintained version.
