### ISSUE TITLE
Update README?

### ISSUE THREAD

**Issue by cnd4** [dvirtz/parquets#7]
The README is the same as https://github.com/kbajalc/parquets, I think it could be updated:

* the introduction tells its a `parquet.js` fork, but this is a `parquets` fork which is itself the `parquet.js` fork
* the `npm install` and `import` instructions tell to use `parquets` but it should be `@dvirtz/parquets`

Do you think we should update it? If yes, do I miss anything which can be added?

**Comment by dvirtz** [comment]
sorry for missing this ticket until now. please tell me if there's still anything missing now.
